//* Copyright (c) 2010 Scott A. Crosby. <scott@sacrosby.com>
//
//Permission is hereby granted, free of charge, to any person obtaining a copy of
//this software and associated documentation files (the "Software"), to deal in
//the Software without restriction, including without limitation the rights to
//use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
//the Software, and to permit persons to whom the Software is furnished to do so,
//subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
//FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
//COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
//IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
//CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: osmproto/fileformat.proto

package osmproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blob struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Raw     []byte                 `protobuf:"bytes,1,opt,name=raw" json:"raw,omitempty"`                         // No compression
	RawSize *int32                 `protobuf:"varint,2,opt,name=raw_size,json=rawSize" json:"raw_size,omitempty"` // When compressed, the uncompressed size
	// Possible compressed versions of the data.
	ZlibData []byte `protobuf:"bytes,3,opt,name=zlib_data,json=zlibData" json:"zlib_data,omitempty"`
	// PROPOSED feature for LZMA compressed data. SUPPORT IS NOT REQUIRED.
	LzmaData []byte `protobuf:"bytes,4,opt,name=lzma_data,json=lzmaData" json:"lzma_data,omitempty"`
	// Formerly used for bzip2 compressed data. Depreciated in 2010.
	//
	// Deprecated: Marked as deprecated in osmproto/fileformat.proto.
	OBSOLETEBzip2Data []byte `protobuf:"bytes,5,opt,name=OBSOLETE_bzip2_data,json=OBSOLETEBzip2Data" json:"OBSOLETE_bzip2_data,omitempty"` // Don't reuse this tag number.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_osmproto_fileformat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_fileformat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_osmproto_fileformat_proto_rawDescGZIP(), []int{0}
}

func (x *Blob) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *Blob) GetRawSize() int32 {
	if x != nil && x.RawSize != nil {
		return *x.RawSize
	}
	return 0
}

func (x *Blob) GetZlibData() []byte {
	if x != nil {
		return x.ZlibData
	}
	return nil
}

func (x *Blob) GetLzmaData() []byte {
	if x != nil {
		return x.LzmaData
	}
	return nil
}

// Deprecated: Marked as deprecated in osmproto/fileformat.proto.
func (x *Blob) GetOBSOLETEBzip2Data() []byte {
	if x != nil {
		return x.OBSOLETEBzip2Data
	}
	return nil
}

type BlobHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Indexdata     []byte                 `protobuf:"bytes,2,opt,name=indexdata" json:"indexdata,omitempty"`
	Datasize      *int32                 `protobuf:"varint,3,req,name=datasize" json:"datasize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobHeader) Reset() {
	*x = BlobHeader{}
	mi := &file_osmproto_fileformat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobHeader) ProtoMessage() {}

func (x *BlobHeader) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_fileformat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobHeader.ProtoReflect.Descriptor instead.
func (*BlobHeader) Descriptor() ([]byte, []int) {
	return file_osmproto_fileformat_proto_rawDescGZIP(), []int{1}
}

func (x *BlobHeader) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *BlobHeader) GetIndexdata() []byte {
	if x != nil {
		return x.Indexdata
	}
	return nil
}

func (x *BlobHeader) GetDatasize() int32 {
	if x != nil && x.Datasize != nil {
		return *x.Datasize
	}
	return 0
}

var File_osmproto_fileformat_proto protoreflect.FileDescriptor

const file_osmproto_fileformat_proto_rawDesc = "" +
	"\n" +
	"\x19osmproto/fileformat.proto\x12\bosmproto\"\xa1\x01\n" +
	"\x04Blob\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\x12\x19\n" +
	"\braw_size\x18\x02 \x01(\x05R\arawSize\x12\x1b\n" +
	"\tzlib_data\x18\x03 \x01(\fR\bzlibData\x12\x1b\n" +
	"\tlzma_data\x18\x04 \x01(\fR\blzmaData\x122\n" +
	"\x13OBSOLETE_bzip2_data\x18\x05 \x01(\fB\x02\x18\x01R\x11OBSOLETEBzip2Data\"Z\n" +
	"\n" +
	"BlobHeader\x12\x12\n" +
	"\x04type\x18\x01 \x02(\tR\x04type\x12\x1c\n" +
	"\tindexdata\x18\x02 \x01(\fR\tindexdata\x12\x1a\n" +
	"\bdatasize\x18\x03 \x02(\x05R\bdatasizeB6\n" +
	"\rcrosby.binaryZ%github.com/royalcat/osmpbfdb/osmproto"

var (
	file_osmproto_fileformat_proto_rawDescOnce sync.Once
	file_osmproto_fileformat_proto_rawDescData []byte
)

func file_osmproto_fileformat_proto_rawDescGZIP() []byte {
	file_osmproto_fileformat_proto_rawDescOnce.Do(func() {
		file_osmproto_fileformat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_osmproto_fileformat_proto_rawDesc), len(file_osmproto_fileformat_proto_rawDesc)))
	})
	return file_osmproto_fileformat_proto_rawDescData
}

var file_osmproto_fileformat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_osmproto_fileformat_proto_goTypes = []any{
	(*Blob)(nil),       // 0: osmproto.Blob
	(*BlobHeader)(nil), // 1: osmproto.BlobHeader
}
var file_osmproto_fileformat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_osmproto_fileformat_proto_init() }
func file_osmproto_fileformat_proto_init() {
	if File_osmproto_fileformat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osmproto_fileformat_proto_rawDesc), len(file_osmproto_fileformat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osmproto_fileformat_proto_goTypes,
		DependencyIndexes: file_osmproto_fileformat_proto_depIdxs,
		MessageInfos:      file_osmproto_fileformat_proto_msgTypes,
	}.Build()
	File_osmproto_fileformat_proto = out.File
	file_osmproto_fileformat_proto_goTypes = nil
	file_osmproto_fileformat_proto_depIdxs = nil
}
