//* Copyright (c) 2010 Scott A. Crosby. <scott@sacrosby.com>
//
//Permission is hereby granted, free of charge, to any person obtaining a copy of
//this software and associated documentation files (the "Software"), to deal in
//the Software without restriction, including without limitation the rights to
//use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
//the Software, and to permit persons to whom the Software is furnished to do so,
//subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
//FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
//COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
//IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
//CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: osmproto/fileformat.proto

package osmproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blob struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Raw               []byte                 `protobuf:"bytes,1,opt,name=raw"`
	xxx_hidden_RawSize           int32                  `protobuf:"varint,2,opt,name=raw_size,json=rawSize"`
	xxx_hidden_ZlibData          []byte                 `protobuf:"bytes,3,opt,name=zlib_data,json=zlibData"`
	xxx_hidden_LzmaData          []byte                 `protobuf:"bytes,4,opt,name=lzma_data,json=lzmaData"`
	xxx_hidden_OBSOLETEBzip2Data []byte                 `protobuf:"bytes,5,opt,name=OBSOLETE_bzip2_data,json=OBSOLETEBzip2Data"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_osmproto_fileformat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_fileformat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Blob) GetRaw() []byte {
	if x != nil {
		return x.xxx_hidden_Raw
	}
	return nil
}

func (x *Blob) GetRawSize() int32 {
	if x != nil {
		return x.xxx_hidden_RawSize
	}
	return 0
}

func (x *Blob) GetZlibData() []byte {
	if x != nil {
		return x.xxx_hidden_ZlibData
	}
	return nil
}

func (x *Blob) GetLzmaData() []byte {
	if x != nil {
		return x.xxx_hidden_LzmaData
	}
	return nil
}

// Deprecated: Marked as deprecated in osmproto/fileformat.proto.
func (x *Blob) GetOBSOLETEBzip2Data() []byte {
	if x != nil {
		return x.xxx_hidden_OBSOLETEBzip2Data
	}
	return nil
}

func (x *Blob) SetRaw(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Raw = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Blob) SetRawSize(v int32) {
	x.xxx_hidden_RawSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Blob) SetZlibData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ZlibData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Blob) SetLzmaData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_LzmaData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

// Deprecated: Marked as deprecated in osmproto/fileformat.proto.
func (x *Blob) SetOBSOLETEBzip2Data(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_OBSOLETEBzip2Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Blob) HasRaw() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Blob) HasRawSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Blob) HasZlibData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Blob) HasLzmaData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

// Deprecated: Marked as deprecated in osmproto/fileformat.proto.
func (x *Blob) HasOBSOLETEBzip2Data() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Blob) ClearRaw() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Raw = nil
}

func (x *Blob) ClearRawSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_RawSize = 0
}

func (x *Blob) ClearZlibData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ZlibData = nil
}

func (x *Blob) ClearLzmaData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_LzmaData = nil
}

// Deprecated: Marked as deprecated in osmproto/fileformat.proto.
func (x *Blob) ClearOBSOLETEBzip2Data() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_OBSOLETEBzip2Data = nil
}

type Blob_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Raw     []byte
	RawSize *int32
	// Possible compressed versions of the data.
	ZlibData []byte
	// PROPOSED feature for LZMA compressed data. SUPPORT IS NOT REQUIRED.
	LzmaData []byte
	// Formerly used for bzip2 compressed data. Depreciated in 2010.
	//
	// Deprecated: Marked as deprecated in osmproto/fileformat.proto.
	OBSOLETEBzip2Data []byte
}

func (b0 Blob_builder) Build() *Blob {
	m0 := &Blob{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Raw != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Raw = b.Raw
	}
	if b.RawSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_RawSize = *b.RawSize
	}
	if b.ZlibData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_ZlibData = b.ZlibData
	}
	if b.LzmaData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_LzmaData = b.LzmaData
	}
	if b.OBSOLETEBzip2Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_OBSOLETEBzip2Data = b.OBSOLETEBzip2Data
	}
	return m0
}

type BlobHeader struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        *string                `protobuf:"bytes,1,opt,name=type"`
	xxx_hidden_Indexdata   []byte                 `protobuf:"bytes,2,opt,name=indexdata"`
	xxx_hidden_Datasize    int32                  `protobuf:"varint,3,opt,name=datasize"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BlobHeader) Reset() {
	*x = BlobHeader{}
	mi := &file_osmproto_fileformat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobHeader) ProtoMessage() {}

func (x *BlobHeader) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_fileformat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BlobHeader) GetType() string {
	if x != nil {
		if x.xxx_hidden_Type != nil {
			return *x.xxx_hidden_Type
		}
		return ""
	}
	return ""
}

func (x *BlobHeader) GetIndexdata() []byte {
	if x != nil {
		return x.xxx_hidden_Indexdata
	}
	return nil
}

func (x *BlobHeader) GetDatasize() int32 {
	if x != nil {
		return x.xxx_hidden_Datasize
	}
	return 0
}

func (x *BlobHeader) SetType(v string) {
	x.xxx_hidden_Type = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *BlobHeader) SetIndexdata(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Indexdata = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *BlobHeader) SetDatasize(v int32) {
	x.xxx_hidden_Datasize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *BlobHeader) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BlobHeader) HasIndexdata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BlobHeader) HasDatasize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *BlobHeader) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = nil
}

func (x *BlobHeader) ClearIndexdata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Indexdata = nil
}

func (x *BlobHeader) ClearDatasize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Datasize = 0
}

type BlobHeader_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type      *string
	Indexdata []byte
	Datasize  *int32
}

func (b0 BlobHeader_builder) Build() *BlobHeader {
	m0 := &BlobHeader{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Type = b.Type
	}
	if b.Indexdata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Indexdata = b.Indexdata
	}
	if b.Datasize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Datasize = *b.Datasize
	}
	return m0
}

var File_osmproto_fileformat_proto protoreflect.FileDescriptor

const file_osmproto_fileformat_proto_rawDesc = "" +
	"\n" +
	"\x19osmproto/fileformat.proto\x12\bosmproto\"\xa1\x01\n" +
	"\x04Blob\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\x12\x19\n" +
	"\braw_size\x18\x02 \x01(\x05R\arawSize\x12\x1b\n" +
	"\tzlib_data\x18\x03 \x01(\fR\bzlibData\x12\x1b\n" +
	"\tlzma_data\x18\x04 \x01(\fR\blzmaData\x122\n" +
	"\x13OBSOLETE_bzip2_data\x18\x05 \x01(\fB\x02\x18\x01R\x11OBSOLETEBzip2Data\"Z\n" +
	"\n" +
	"BlobHeader\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\tindexdata\x18\x02 \x01(\fR\tindexdata\x12\x1a\n" +
	"\bdatasize\x18\x03 \x01(\x05R\bdatasizeB;\n" +
	"\rcrosby.binaryZ%github.com/royalcat/osmpbfdb/osmproto\x92\x03\x02 \x03b\beditionsp\xe9\a"

var file_osmproto_fileformat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_osmproto_fileformat_proto_goTypes = []any{
	(*Blob)(nil),       // 0: osmproto.Blob
	(*BlobHeader)(nil), // 1: osmproto.BlobHeader
}
var file_osmproto_fileformat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_osmproto_fileformat_proto_init() }
func file_osmproto_fileformat_proto_init() {
	if File_osmproto_fileformat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osmproto_fileformat_proto_rawDesc), len(file_osmproto_fileformat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osmproto_fileformat_proto_goTypes,
		DependencyIndexes: file_osmproto_fileformat_proto_depIdxs,
		MessageInfos:      file_osmproto_fileformat_proto_msgTypes,
	}.Build()
	File_osmproto_fileformat_proto = out.File
	file_osmproto_fileformat_proto_goTypes = nil
	file_osmproto_fileformat_proto_depIdxs = nil
}
