//* Copyright (c) 2010 Scott A. Crosby. <scott@sacrosby.com>
//
//Permission is hereby granted, free of charge, to any person obtaining a copy of
//this software and associated documentation files (the "Software"), to deal in
//the Software without restriction, including without limitation the rights to
//use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
//of the Software, and to permit persons to whom the Software is furnished to do
//so, subject to the following conditions:
//
//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.
//
//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: osmproto/osmformat.proto

package osmproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Relation_MemberType int32

const (
	Relation_NODE     Relation_MemberType = 0
	Relation_WAY      Relation_MemberType = 1
	Relation_RELATION Relation_MemberType = 2
)

// Enum value maps for Relation_MemberType.
var (
	Relation_MemberType_name = map[int32]string{
		0: "NODE",
		1: "WAY",
		2: "RELATION",
	}
	Relation_MemberType_value = map[string]int32{
		"NODE":     0,
		"WAY":      1,
		"RELATION": 2,
	}
)

func (x Relation_MemberType) Enum() *Relation_MemberType {
	p := new(Relation_MemberType)
	*p = x
	return p
}

func (x Relation_MemberType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Relation_MemberType) Descriptor() protoreflect.EnumDescriptor {
	return file_osmproto_osmformat_proto_enumTypes[0].Descriptor()
}

func (Relation_MemberType) Type() protoreflect.EnumType {
	return &file_osmproto_osmformat_proto_enumTypes[0]
}

func (x Relation_MemberType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type HeaderBlock struct {
	state                                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Bbox                             *HeaderBBox            `protobuf:"bytes,1,opt,name=bbox"`
	xxx_hidden_RequiredFeatures                 []string               `protobuf:"bytes,4,rep,name=required_features,json=requiredFeatures"`
	xxx_hidden_OptionalFeatures                 []string               `protobuf:"bytes,5,rep,name=optional_features,json=optionalFeatures"`
	xxx_hidden_Writingprogram                   *string                `protobuf:"bytes,16,opt,name=writingprogram"`
	xxx_hidden_Source                           *string                `protobuf:"bytes,17,opt,name=source"`
	xxx_hidden_OsmosisReplicationTimestamp      int64                  `protobuf:"varint,32,opt,name=osmosis_replication_timestamp,json=osmosisReplicationTimestamp"`
	xxx_hidden_OsmosisReplicationSequenceNumber int64                  `protobuf:"varint,33,opt,name=osmosis_replication_sequence_number,json=osmosisReplicationSequenceNumber"`
	xxx_hidden_OsmosisReplicationBaseUrl        *string                `protobuf:"bytes,34,opt,name=osmosis_replication_base_url,json=osmosisReplicationBaseUrl"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HeaderBlock) Reset() {
	*x = HeaderBlock{}
	mi := &file_osmproto_osmformat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderBlock) ProtoMessage() {}

func (x *HeaderBlock) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_osmformat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HeaderBlock) GetBbox() *HeaderBBox {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Bbox) {
				protoimpl.X.UnmarshalField(x, 1)
			}
			var rv *HeaderBBox
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Bbox), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *HeaderBlock) GetRequiredFeatures() []string {
	if x != nil {
		return x.xxx_hidden_RequiredFeatures
	}
	return nil
}

func (x *HeaderBlock) GetOptionalFeatures() []string {
	if x != nil {
		return x.xxx_hidden_OptionalFeatures
	}
	return nil
}

func (x *HeaderBlock) GetWritingprogram() string {
	if x != nil {
		if x.xxx_hidden_Writingprogram != nil {
			return *x.xxx_hidden_Writingprogram
		}
		return ""
	}
	return ""
}

func (x *HeaderBlock) GetSource() string {
	if x != nil {
		if x.xxx_hidden_Source != nil {
			return *x.xxx_hidden_Source
		}
		return ""
	}
	return ""
}

func (x *HeaderBlock) GetOsmosisReplicationTimestamp() int64 {
	if x != nil {
		return x.xxx_hidden_OsmosisReplicationTimestamp
	}
	return 0
}

func (x *HeaderBlock) GetOsmosisReplicationSequenceNumber() int64 {
	if x != nil {
		return x.xxx_hidden_OsmosisReplicationSequenceNumber
	}
	return 0
}

func (x *HeaderBlock) GetOsmosisReplicationBaseUrl() string {
	if x != nil {
		if x.xxx_hidden_OsmosisReplicationBaseUrl != nil {
			return *x.xxx_hidden_OsmosisReplicationBaseUrl
		}
		return ""
	}
	return ""
}

func (x *HeaderBlock) SetBbox(v *HeaderBBox) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Bbox, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
	}
}

func (x *HeaderBlock) SetRequiredFeatures(v []string) {
	x.xxx_hidden_RequiredFeatures = v
}

func (x *HeaderBlock) SetOptionalFeatures(v []string) {
	x.xxx_hidden_OptionalFeatures = v
}

func (x *HeaderBlock) SetWritingprogram(v string) {
	x.xxx_hidden_Writingprogram = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *HeaderBlock) SetSource(v string) {
	x.xxx_hidden_Source = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *HeaderBlock) SetOsmosisReplicationTimestamp(v int64) {
	x.xxx_hidden_OsmosisReplicationTimestamp = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *HeaderBlock) SetOsmosisReplicationSequenceNumber(v int64) {
	x.xxx_hidden_OsmosisReplicationSequenceNumber = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *HeaderBlock) SetOsmosisReplicationBaseUrl(v string) {
	x.xxx_hidden_OsmosisReplicationBaseUrl = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *HeaderBlock) HasBbox() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HeaderBlock) HasWritingprogram() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *HeaderBlock) HasSource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *HeaderBlock) HasOsmosisReplicationTimestamp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *HeaderBlock) HasOsmosisReplicationSequenceNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *HeaderBlock) HasOsmosisReplicationBaseUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *HeaderBlock) ClearBbox() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Bbox, (*HeaderBBox)(nil))
}

func (x *HeaderBlock) ClearWritingprogram() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Writingprogram = nil
}

func (x *HeaderBlock) ClearSource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Source = nil
}

func (x *HeaderBlock) ClearOsmosisReplicationTimestamp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_OsmosisReplicationTimestamp = 0
}

func (x *HeaderBlock) ClearOsmosisReplicationSequenceNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_OsmosisReplicationSequenceNumber = 0
}

func (x *HeaderBlock) ClearOsmosisReplicationBaseUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_OsmosisReplicationBaseUrl = nil
}

type HeaderBlock_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Bbox *HeaderBBox
	// Additional tags to aid in parsing this dataset
	RequiredFeatures []string
	OptionalFeatures []string
	Writingprogram   *string
	Source           *string
	// Replication timestamp, expressed in seconds since the epoch,
	// otherwise the same value as in the "timestamp=..." field
	// in the state.txt file used by Osmosis.
	OsmosisReplicationTimestamp *int64
	// Replication sequence number (sequenceNumber in state.txt).
	OsmosisReplicationSequenceNumber *int64
	// Replication base URL (from Osmosis' configuration.txt file).
	OsmosisReplicationBaseUrl *string
}

func (b0 HeaderBlock_builder) Build() *HeaderBlock {
	m0 := &HeaderBlock{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Bbox != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Bbox = b.Bbox
	}
	x.xxx_hidden_RequiredFeatures = b.RequiredFeatures
	x.xxx_hidden_OptionalFeatures = b.OptionalFeatures
	if b.Writingprogram != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Writingprogram = b.Writingprogram
	}
	if b.Source != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Source = b.Source
	}
	if b.OsmosisReplicationTimestamp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_OsmosisReplicationTimestamp = *b.OsmosisReplicationTimestamp
	}
	if b.OsmosisReplicationSequenceNumber != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_OsmosisReplicationSequenceNumber = *b.OsmosisReplicationSequenceNumber
	}
	if b.OsmosisReplicationBaseUrl != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_OsmosisReplicationBaseUrl = b.OsmosisReplicationBaseUrl
	}
	return m0
}

type HeaderBBox struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Left        int64                  `protobuf:"zigzag64,1,opt,name=left"`
	xxx_hidden_Right       int64                  `protobuf:"zigzag64,2,opt,name=right"`
	xxx_hidden_Top         int64                  `protobuf:"zigzag64,3,opt,name=top"`
	xxx_hidden_Bottom      int64                  `protobuf:"zigzag64,4,opt,name=bottom"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HeaderBBox) Reset() {
	*x = HeaderBBox{}
	mi := &file_osmproto_osmformat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderBBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderBBox) ProtoMessage() {}

func (x *HeaderBBox) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_osmformat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HeaderBBox) GetLeft() int64 {
	if x != nil {
		return x.xxx_hidden_Left
	}
	return 0
}

func (x *HeaderBBox) GetRight() int64 {
	if x != nil {
		return x.xxx_hidden_Right
	}
	return 0
}

func (x *HeaderBBox) GetTop() int64 {
	if x != nil {
		return x.xxx_hidden_Top
	}
	return 0
}

func (x *HeaderBBox) GetBottom() int64 {
	if x != nil {
		return x.xxx_hidden_Bottom
	}
	return 0
}

func (x *HeaderBBox) SetLeft(v int64) {
	x.xxx_hidden_Left = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *HeaderBBox) SetRight(v int64) {
	x.xxx_hidden_Right = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *HeaderBBox) SetTop(v int64) {
	x.xxx_hidden_Top = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *HeaderBBox) SetBottom(v int64) {
	x.xxx_hidden_Bottom = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *HeaderBBox) HasLeft() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *HeaderBBox) HasRight() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *HeaderBBox) HasTop() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *HeaderBBox) HasBottom() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *HeaderBBox) ClearLeft() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Left = 0
}

func (x *HeaderBBox) ClearRight() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Right = 0
}

func (x *HeaderBBox) ClearTop() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Top = 0
}

func (x *HeaderBBox) ClearBottom() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Bottom = 0
}

type HeaderBBox_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Left   *int64
	Right  *int64
	Top    *int64
	Bottom *int64
}

func (b0 HeaderBBox_builder) Build() *HeaderBBox {
	m0 := &HeaderBBox{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Left != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Left = *b.Left
	}
	if b.Right != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Right = *b.Right
	}
	if b.Top != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Top = *b.Top
	}
	if b.Bottom != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Bottom = *b.Bottom
	}
	return m0
}

type PrimitiveBlock struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Stringtable     *StringTable           `protobuf:"bytes,1,opt,name=stringtable"`
	xxx_hidden_Primitivegroup  *[]*PrimitiveGroup     `protobuf:"bytes,2,rep,name=primitivegroup"`
	xxx_hidden_Granularity     int32                  `protobuf:"varint,17,opt,name=granularity,def=100"`
	xxx_hidden_LatOffset       int64                  `protobuf:"varint,19,opt,name=lat_offset,json=latOffset,def=0"`
	xxx_hidden_LonOffset       int64                  `protobuf:"varint,20,opt,name=lon_offset,json=lonOffset,def=0"`
	xxx_hidden_DateGranularity int32                  `protobuf:"varint,18,opt,name=date_granularity,json=dateGranularity,def=1000"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

// Default values for PrimitiveBlock fields.
const (
	Default_PrimitiveBlock_Granularity     = int32(100)
	Default_PrimitiveBlock_LatOffset       = int64(0)
	Default_PrimitiveBlock_LonOffset       = int64(0)
	Default_PrimitiveBlock_DateGranularity = int32(1000)
)

func (x *PrimitiveBlock) Reset() {
	*x = PrimitiveBlock{}
	mi := &file_osmproto_osmformat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimitiveBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimitiveBlock) ProtoMessage() {}

func (x *PrimitiveBlock) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_osmformat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrimitiveBlock) GetStringtable() *StringTable {
	if x != nil {
		return x.xxx_hidden_Stringtable
	}
	return nil
}

func (x *PrimitiveBlock) GetPrimitivegroup() []*PrimitiveGroup {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Primitivegroup) {
				protoimpl.X.UnmarshalField(x, 2)
			}
			var rv *[]*PrimitiveGroup
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Primitivegroup), protoimpl.Pointer(&rv))
			return *rv
		}
	}
	return nil
}

func (x *PrimitiveBlock) GetGranularity() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Granularity
		}
	}
	return Default_PrimitiveBlock_Granularity
}

func (x *PrimitiveBlock) GetLatOffset() int64 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_LatOffset
		}
	}
	return Default_PrimitiveBlock_LatOffset
}

func (x *PrimitiveBlock) GetLonOffset() int64 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_LonOffset
		}
	}
	return Default_PrimitiveBlock_LonOffset
}

func (x *PrimitiveBlock) GetDateGranularity() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_DateGranularity
		}
	}
	return Default_PrimitiveBlock_DateGranularity
}

func (x *PrimitiveBlock) SetStringtable(v *StringTable) {
	x.xxx_hidden_Stringtable = v
}

func (x *PrimitiveBlock) SetPrimitivegroup(v []*PrimitiveGroup) {
	var sv *[]*PrimitiveGroup
	protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Primitivegroup), protoimpl.Pointer(&sv))
	if sv == nil {
		sv = &[]*PrimitiveGroup{}
		protoimpl.X.AtomicInitializePointer(protoimpl.Pointer(&x.xxx_hidden_Primitivegroup), protoimpl.Pointer(&sv))
	}
	*sv = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *PrimitiveBlock) SetGranularity(v int32) {
	x.xxx_hidden_Granularity = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *PrimitiveBlock) SetLatOffset(v int64) {
	x.xxx_hidden_LatOffset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *PrimitiveBlock) SetLonOffset(v int64) {
	x.xxx_hidden_LonOffset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *PrimitiveBlock) SetDateGranularity(v int32) {
	x.xxx_hidden_DateGranularity = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *PrimitiveBlock) HasStringtable() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Stringtable != nil
}

func (x *PrimitiveBlock) HasGranularity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PrimitiveBlock) HasLatOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PrimitiveBlock) HasLonOffset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *PrimitiveBlock) HasDateGranularity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *PrimitiveBlock) ClearStringtable() {
	x.xxx_hidden_Stringtable = nil
}

func (x *PrimitiveBlock) ClearGranularity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
}

func (x *PrimitiveBlock) ClearLatOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
}

func (x *PrimitiveBlock) ClearLonOffset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
}

func (x *PrimitiveBlock) ClearDateGranularity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
}

type PrimitiveBlock_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Stringtable    *StringTable
	Primitivegroup []*PrimitiveGroup
	// Granularity, units of nanodegrees, used to store coordinates in this block.
	Granularity *int32
	// Offset value between the output coordinates and the granularity grid in
	// units of nanodegrees.
	LatOffset *int64
	LonOffset *int64
	// Granularity of dates, normally represented in units of milliseconds since
	// the 1970 epoch.
	DateGranularity *int32
}

func (b0 PrimitiveBlock_builder) Build() *PrimitiveBlock {
	m0 := &PrimitiveBlock{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Stringtable = b.Stringtable
	if b.Primitivegroup != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Primitivegroup = &b.Primitivegroup
	}
	if b.Granularity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Granularity = *b.Granularity
	}
	if b.LatOffset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_LatOffset = *b.LatOffset
	}
	if b.LonOffset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_LonOffset = *b.LonOffset
	}
	if b.DateGranularity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_DateGranularity = *b.DateGranularity
	}
	return m0
}

// Group of OSMPrimitives. All primitives in a group must be the same type.
type PrimitiveGroup struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes      *[]*Node               `protobuf:"bytes,1,rep,name=nodes"`
	xxx_hidden_Dense      *DenseNodes            `protobuf:"bytes,2,opt,name=dense"`
	xxx_hidden_Ways       *[]*Way                `protobuf:"bytes,3,rep,name=ways"`
	xxx_hidden_Relations  *[]*Relation           `protobuf:"bytes,4,rep,name=relations"`
	xxx_hidden_Changesets *[]*ChangeSet          `protobuf:"bytes,5,rep,name=changesets"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PrimitiveGroup) Reset() {
	*x = PrimitiveGroup{}
	mi := &file_osmproto_osmformat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrimitiveGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrimitiveGroup) ProtoMessage() {}

func (x *PrimitiveGroup) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_osmformat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrimitiveGroup) GetNodes() []*Node {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Nodes) {
				protoimpl.X.UnmarshalField(x, 1)
			}
			var rv *[]*Node
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Nodes), protoimpl.Pointer(&rv))
			return *rv
		}
	}
	return nil
}

func (x *PrimitiveGroup) GetDense() *DenseNodes {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Dense) {
				protoimpl.X.UnmarshalField(x, 2)
			}
			var rv *DenseNodes
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Dense), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *PrimitiveGroup) GetWays() []*Way {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Ways) {
				protoimpl.X.UnmarshalField(x, 3)
			}
			var rv *[]*Way
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Ways), protoimpl.Pointer(&rv))
			return *rv
		}
	}
	return nil
}

func (x *PrimitiveGroup) GetRelations() []*Relation {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Relations) {
				protoimpl.X.UnmarshalField(x, 4)
			}
			var rv *[]*Relation
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Relations), protoimpl.Pointer(&rv))
			return *rv
		}
	}
	return nil
}

func (x *PrimitiveGroup) GetChangesets() []*ChangeSet {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Changesets) {
				protoimpl.X.UnmarshalField(x, 5)
			}
			var rv *[]*ChangeSet
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Changesets), protoimpl.Pointer(&rv))
			return *rv
		}
	}
	return nil
}

func (x *PrimitiveGroup) SetNodes(v []*Node) {
	var sv *[]*Node
	protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Nodes), protoimpl.Pointer(&sv))
	if sv == nil {
		sv = &[]*Node{}
		protoimpl.X.AtomicInitializePointer(protoimpl.Pointer(&x.xxx_hidden_Nodes), protoimpl.Pointer(&sv))
	}
	*sv = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *PrimitiveGroup) SetDense(v *DenseNodes) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Dense, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
	}
}

func (x *PrimitiveGroup) SetWays(v []*Way) {
	var sv *[]*Way
	protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Ways), protoimpl.Pointer(&sv))
	if sv == nil {
		sv = &[]*Way{}
		protoimpl.X.AtomicInitializePointer(protoimpl.Pointer(&x.xxx_hidden_Ways), protoimpl.Pointer(&sv))
	}
	*sv = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *PrimitiveGroup) SetRelations(v []*Relation) {
	var sv *[]*Relation
	protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Relations), protoimpl.Pointer(&sv))
	if sv == nil {
		sv = &[]*Relation{}
		protoimpl.X.AtomicInitializePointer(protoimpl.Pointer(&x.xxx_hidden_Relations), protoimpl.Pointer(&sv))
	}
	*sv = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *PrimitiveGroup) SetChangesets(v []*ChangeSet) {
	var sv *[]*ChangeSet
	protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Changesets), protoimpl.Pointer(&sv))
	if sv == nil {
		sv = &[]*ChangeSet{}
		protoimpl.X.AtomicInitializePointer(protoimpl.Pointer(&x.xxx_hidden_Changesets), protoimpl.Pointer(&sv))
	}
	*sv = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *PrimitiveGroup) HasDense() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PrimitiveGroup) ClearDense() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Dense, (*DenseNodes)(nil))
}

type PrimitiveGroup_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Nodes      []*Node
	Dense      *DenseNodes
	Ways       []*Way
	Relations  []*Relation
	Changesets []*ChangeSet
}

func (b0 PrimitiveGroup_builder) Build() *PrimitiveGroup {
	m0 := &PrimitiveGroup{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Nodes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Nodes = &b.Nodes
	}
	if b.Dense != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Dense = b.Dense
	}
	if b.Ways != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Ways = &b.Ways
	}
	if b.Relations != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Relations = &b.Relations
	}
	if b.Changesets != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Changesets = &b.Changesets
	}
	return m0
}

// * String table, contains the common strings in each block.
//
// Note that we reserve index '0' as a delimiter, so the entry at that
// index in the table is ALWAYS blank and unused.
type StringTable struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_S  []string               `protobuf:"bytes,1,rep,name=s"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringTable) Reset() {
	*x = StringTable{}
	mi := &file_osmproto_osmformat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringTable) ProtoMessage() {}

func (x *StringTable) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_osmformat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StringTable) GetS() []string {
	if x != nil {
		return x.xxx_hidden_S
	}
	return nil
}

func (x *StringTable) SetS(v []string) {
	x.xxx_hidden_S = v
}

type StringTable_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	S []string
}

func (b0 StringTable_builder) Build() *StringTable {
	m0 := &StringTable{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_S = b.S
	return m0
}

// Optional metadata that may be included into each primitive.
type Info struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Version     int32                  `protobuf:"varint,1,opt,name=version,def=-1"`
	xxx_hidden_Timestamp   int64                  `protobuf:"varint,2,opt,name=timestamp"`
	xxx_hidden_Changeset   int64                  `protobuf:"varint,3,opt,name=changeset"`
	xxx_hidden_Uid         int32                  `protobuf:"varint,4,opt,name=uid"`
	xxx_hidden_UserSid     uint32                 `protobuf:"varint,5,opt,name=user_sid,json=userSid"`
	xxx_hidden_Visible     bool                   `protobuf:"varint,6,opt,name=visible"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

// Default values for Info fields.
const (
	Default_Info_Version = int32(-1)
)

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_osmproto_osmformat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_osmformat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Info) GetVersion() int32 {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Version
		}
	}
	return Default_Info_Version
}

func (x *Info) GetTimestamp() int64 {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return 0
}

func (x *Info) GetChangeset() int64 {
	if x != nil {
		return x.xxx_hidden_Changeset
	}
	return 0
}

func (x *Info) GetUid() int32 {
	if x != nil {
		return x.xxx_hidden_Uid
	}
	return 0
}

func (x *Info) GetUserSid() uint32 {
	if x != nil {
		return x.xxx_hidden_UserSid
	}
	return 0
}

func (x *Info) GetVisible() bool {
	if x != nil {
		return x.xxx_hidden_Visible
	}
	return false
}

func (x *Info) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *Info) SetTimestamp(v int64) {
	x.xxx_hidden_Timestamp = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *Info) SetChangeset(v int64) {
	x.xxx_hidden_Changeset = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *Info) SetUid(v int32) {
	x.xxx_hidden_Uid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *Info) SetUserSid(v uint32) {
	x.xxx_hidden_UserSid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *Info) SetVisible(v bool) {
	x.xxx_hidden_Visible = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *Info) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Info) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Info) HasChangeset() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Info) HasUid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Info) HasUserSid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Info) HasVisible() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Info) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
}

func (x *Info) ClearTimestamp() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Timestamp = 0
}

func (x *Info) ClearChangeset() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Changeset = 0
}

func (x *Info) ClearUid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Uid = 0
}

func (x *Info) ClearUserSid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_UserSid = 0
}

func (x *Info) ClearVisible() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Visible = false
}

type Info_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Version   *int32
	Timestamp *int64
	Changeset *int64
	Uid       *int32
	UserSid   *uint32
	// The visible flag is used to store history information. It indicates that
	// the current object version has been created by a delete operation on the
	// OSM API.
	// When a writer sets this flag, it MUST add a required_features tag with
	// value "HistoricalInformation" to the HeaderBlock.
	// If this flag is not available for some object it MUST be assumed to be
	// true if the file has the required_features tag "HistoricalInformation"
	// set.
	Visible *bool
}

func (b0 Info_builder) Build() *Info {
	m0 := &Info{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Version = *b.Version
	}
	if b.Timestamp != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Timestamp = *b.Timestamp
	}
	if b.Changeset != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Changeset = *b.Changeset
	}
	if b.Uid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Uid = *b.Uid
	}
	if b.UserSid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_UserSid = *b.UserSid
	}
	if b.Visible != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Visible = *b.Visible
	}
	return m0
}

// * Optional metadata that may be included into each primitive. Special dense
// format used in DenseNodes.
type DenseInfo struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Version   []int32                `protobuf:"varint,1,rep,packed,name=version"`
	xxx_hidden_Timestamp []int64                `protobuf:"zigzag64,2,rep,packed,name=timestamp"`
	xxx_hidden_Changeset []int64                `protobuf:"zigzag64,3,rep,packed,name=changeset"`
	xxx_hidden_Uid       []int32                `protobuf:"zigzag32,4,rep,packed,name=uid"`
	xxx_hidden_UserSid   []int32                `protobuf:"zigzag32,5,rep,packed,name=user_sid,json=userSid"`
	xxx_hidden_Visible   []bool                 `protobuf:"varint,6,rep,packed,name=visible"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DenseInfo) Reset() {
	*x = DenseInfo{}
	mi := &file_osmproto_osmformat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenseInfo) ProtoMessage() {}

func (x *DenseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_osmformat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DenseInfo) GetVersion() []int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return nil
}

func (x *DenseInfo) GetTimestamp() []int64 {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *DenseInfo) GetChangeset() []int64 {
	if x != nil {
		return x.xxx_hidden_Changeset
	}
	return nil
}

func (x *DenseInfo) GetUid() []int32 {
	if x != nil {
		return x.xxx_hidden_Uid
	}
	return nil
}

func (x *DenseInfo) GetUserSid() []int32 {
	if x != nil {
		return x.xxx_hidden_UserSid
	}
	return nil
}

func (x *DenseInfo) GetVisible() []bool {
	if x != nil {
		return x.xxx_hidden_Visible
	}
	return nil
}

func (x *DenseInfo) SetVersion(v []int32) {
	x.xxx_hidden_Version = v
}

func (x *DenseInfo) SetTimestamp(v []int64) {
	x.xxx_hidden_Timestamp = v
}

func (x *DenseInfo) SetChangeset(v []int64) {
	x.xxx_hidden_Changeset = v
}

func (x *DenseInfo) SetUid(v []int32) {
	x.xxx_hidden_Uid = v
}

func (x *DenseInfo) SetUserSid(v []int32) {
	x.xxx_hidden_UserSid = v
}

func (x *DenseInfo) SetVisible(v []bool) {
	x.xxx_hidden_Visible = v
}

type DenseInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Version   []int32
	Timestamp []int64
	Changeset []int64
	Uid       []int32
	UserSid   []int32
	// The visible flag is used to store history information. It indicates that
	// the current object version has been created by a delete operation on the
	// OSM API.
	// When a writer sets this flag, it MUST add a required_features tag with
	// value "HistoricalInformation" to the HeaderBlock.
	// If this flag is not available for some object it MUST be assumed to be
	// true if the file has the required_features tag "HistoricalInformation"
	// set.
	Visible []bool
}

func (b0 DenseInfo_builder) Build() *DenseInfo {
	m0 := &DenseInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Version = b.Version
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_Changeset = b.Changeset
	x.xxx_hidden_Uid = b.Uid
	x.xxx_hidden_UserSid = b.UserSid
	x.xxx_hidden_Visible = b.Visible
	return m0
}

// This is kept for backwards compatibility but not used anywhere.
type ChangeSet struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int64                  `protobuf:"varint,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChangeSet) Reset() {
	*x = ChangeSet{}
	mi := &file_osmproto_osmformat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeSet) ProtoMessage() {}

func (x *ChangeSet) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_osmformat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChangeSet) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *ChangeSet) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ChangeSet) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ChangeSet) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

type ChangeSet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int64
}

func (b0 ChangeSet_builder) Build() *ChangeSet {
	m0 := &ChangeSet{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = *b.Id
	}
	return m0
}

type Node struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id   int64                  `protobuf:"zigzag64,1,opt,name=id"`
	xxx_hidden_Keys []uint32               `protobuf:"varint,2,rep,packed,name=keys"`
	xxx_hidden_Vals []uint32               `protobuf:"varint,3,rep,packed,name=vals"`
	xxx_hidden_Info *Info                  `protobuf:"bytes,4,opt,name=info"`
	xxx_hidden_Lat  int64                  `protobuf:"zigzag64,8,opt,name=lat"`
	xxx_hidden_Lon  int64                  `protobuf:"zigzag64,9,opt,name=lon"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_osmproto_osmformat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_osmformat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Node) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Node) GetKeys() []uint32 {
	if x != nil {
		return x.xxx_hidden_Keys
	}
	return nil
}

func (x *Node) GetVals() []uint32 {
	if x != nil {
		return x.xxx_hidden_Vals
	}
	return nil
}

func (x *Node) GetInfo() *Info {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Info) {
				protoimpl.X.UnmarshalField(x, 4)
			}
			var rv *Info
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Info), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *Node) GetLat() int64 {
	if x != nil {
		return x.xxx_hidden_Lat
	}
	return 0
}

func (x *Node) GetLon() int64 {
	if x != nil {
		return x.xxx_hidden_Lon
	}
	return 0
}

func (x *Node) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *Node) SetKeys(v []uint32) {
	x.xxx_hidden_Keys = v
}

func (x *Node) SetVals(v []uint32) {
	x.xxx_hidden_Vals = v
}

func (x *Node) SetInfo(v *Info) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Info, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
	}
}

func (x *Node) SetLat(v int64) {
	x.xxx_hidden_Lat = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *Node) SetLon(v int64) {
	x.xxx_hidden_Lon = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *Node) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Node) HasInfo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Node) HasLat() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Node) HasLon() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Node) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *Node) ClearInfo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Info, (*Info)(nil))
}

func (x *Node) ClearLat() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Lat = 0
}

func (x *Node) ClearLon() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Lon = 0
}

type Node_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int64
	// Parallel arrays.
	Keys []uint32
	Vals []uint32
	Info *Info
	Lat  *int64
	Lon  *int64
}

func (b0 Node_builder) Build() *Node {
	m0 := &Node{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = *b.Id
	}
	x.xxx_hidden_Keys = b.Keys
	x.xxx_hidden_Vals = b.Vals
	if b.Info != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Info = b.Info
	}
	if b.Lat != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Lat = *b.Lat
	}
	if b.Lon != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_Lon = *b.Lon
	}
	return m0
}

type DenseNodes struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        []int64                `protobuf:"zigzag64,1,rep,packed,name=id"`
	xxx_hidden_Denseinfo *DenseInfo             `protobuf:"bytes,5,opt,name=denseinfo"`
	xxx_hidden_Lat       []int64                `protobuf:"zigzag64,8,rep,packed,name=lat"`
	xxx_hidden_Lon       []int64                `protobuf:"zigzag64,9,rep,packed,name=lon"`
	xxx_hidden_KeysVals  []int32                `protobuf:"varint,10,rep,packed,name=keys_vals,json=keysVals"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DenseNodes) Reset() {
	*x = DenseNodes{}
	mi := &file_osmproto_osmformat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenseNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenseNodes) ProtoMessage() {}

func (x *DenseNodes) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_osmformat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DenseNodes) GetId() []int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *DenseNodes) GetDenseinfo() *DenseInfo {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Denseinfo) {
				protoimpl.X.UnmarshalField(x, 5)
			}
			var rv *DenseInfo
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Denseinfo), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *DenseNodes) GetLat() []int64 {
	if x != nil {
		return x.xxx_hidden_Lat
	}
	return nil
}

func (x *DenseNodes) GetLon() []int64 {
	if x != nil {
		return x.xxx_hidden_Lon
	}
	return nil
}

func (x *DenseNodes) GetKeysVals() []int32 {
	if x != nil {
		return x.xxx_hidden_KeysVals
	}
	return nil
}

func (x *DenseNodes) SetId(v []int64) {
	x.xxx_hidden_Id = v
}

func (x *DenseNodes) SetDenseinfo(v *DenseInfo) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Denseinfo, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
	}
}

func (x *DenseNodes) SetLat(v []int64) {
	x.xxx_hidden_Lat = v
}

func (x *DenseNodes) SetLon(v []int64) {
	x.xxx_hidden_Lon = v
}

func (x *DenseNodes) SetKeysVals(v []int32) {
	x.xxx_hidden_KeysVals = v
}

func (x *DenseNodes) HasDenseinfo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DenseNodes) ClearDenseinfo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Denseinfo, (*DenseInfo)(nil))
}

type DenseNodes_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id        []int64
	Denseinfo *DenseInfo
	Lat       []int64
	Lon       []int64
	// Special packing of keys and vals into one array. May be empty if all nodes
	// in this block are tagless.
	KeysVals []int32
}

func (b0 DenseNodes_builder) Build() *DenseNodes {
	m0 := &DenseNodes{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	if b.Denseinfo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Denseinfo = b.Denseinfo
	}
	x.xxx_hidden_Lat = b.Lat
	x.xxx_hidden_Lon = b.Lon
	x.xxx_hidden_KeysVals = b.KeysVals
	return m0
}

type Way struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id   int64                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Keys []uint32               `protobuf:"varint,2,rep,packed,name=keys"`
	xxx_hidden_Vals []uint32               `protobuf:"varint,3,rep,packed,name=vals"`
	xxx_hidden_Info *Info                  `protobuf:"bytes,4,opt,name=info"`
	xxx_hidden_Refs []int64                `protobuf:"zigzag64,8,rep,packed,name=refs"`
	xxx_hidden_Lat  []int64                `protobuf:"zigzag64,9,rep,packed,name=lat"`
	xxx_hidden_Lon  []int64                `protobuf:"zigzag64,10,rep,packed,name=lon"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Way) Reset() {
	*x = Way{}
	mi := &file_osmproto_osmformat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Way) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Way) ProtoMessage() {}

func (x *Way) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_osmformat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Way) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Way) GetKeys() []uint32 {
	if x != nil {
		return x.xxx_hidden_Keys
	}
	return nil
}

func (x *Way) GetVals() []uint32 {
	if x != nil {
		return x.xxx_hidden_Vals
	}
	return nil
}

func (x *Way) GetInfo() *Info {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Info) {
				protoimpl.X.UnmarshalField(x, 4)
			}
			var rv *Info
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Info), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *Way) GetRefs() []int64 {
	if x != nil {
		return x.xxx_hidden_Refs
	}
	return nil
}

func (x *Way) GetLat() []int64 {
	if x != nil {
		return x.xxx_hidden_Lat
	}
	return nil
}

func (x *Way) GetLon() []int64 {
	if x != nil {
		return x.xxx_hidden_Lon
	}
	return nil
}

func (x *Way) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *Way) SetKeys(v []uint32) {
	x.xxx_hidden_Keys = v
}

func (x *Way) SetVals(v []uint32) {
	x.xxx_hidden_Vals = v
}

func (x *Way) SetInfo(v *Info) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Info, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
	}
}

func (x *Way) SetRefs(v []int64) {
	x.xxx_hidden_Refs = v
}

func (x *Way) SetLat(v []int64) {
	x.xxx_hidden_Lat = v
}

func (x *Way) SetLon(v []int64) {
	x.xxx_hidden_Lon = v
}

func (x *Way) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Way) HasInfo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Way) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *Way) ClearInfo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Info, (*Info)(nil))
}

type Way_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int64
	// Parallel arrays.
	Keys []uint32
	Vals []uint32
	Info *Info
	Refs []int64
	// The following two fields are optional. They are only used in a special
	// format where node locations are also added to the ways. This makes the
	// files larger, but allows creating way geometries directly.
	//
	// If this is used, you MUST set the optional_features tag "LocationsOnWays"
	// and the number of values in refs, lat, and lon MUST be the same.
	Lat []int64
	Lon []int64
}

func (b0 Way_builder) Build() *Way {
	m0 := &Way{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = *b.Id
	}
	x.xxx_hidden_Keys = b.Keys
	x.xxx_hidden_Vals = b.Vals
	if b.Info != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Info = b.Info
	}
	x.xxx_hidden_Refs = b.Refs
	x.xxx_hidden_Lat = b.Lat
	x.xxx_hidden_Lon = b.Lon
	return m0
}

type Relation struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id       int64                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Keys     []uint32               `protobuf:"varint,2,rep,packed,name=keys"`
	xxx_hidden_Vals     []uint32               `protobuf:"varint,3,rep,packed,name=vals"`
	xxx_hidden_Info     *Info                  `protobuf:"bytes,4,opt,name=info"`
	xxx_hidden_RolesSid []int32                `protobuf:"varint,8,rep,packed,name=roles_sid,json=rolesSid"`
	xxx_hidden_Memids   []int64                `protobuf:"zigzag64,9,rep,packed,name=memids"`
	xxx_hidden_Types    []Relation_MemberType  `protobuf:"varint,10,rep,packed,name=types,enum=osmproto.Relation_MemberType"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_osmproto_osmformat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_osmproto_osmformat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Relation) GetId() int64 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Relation) GetKeys() []uint32 {
	if x != nil {
		return x.xxx_hidden_Keys
	}
	return nil
}

func (x *Relation) GetVals() []uint32 {
	if x != nil {
		return x.xxx_hidden_Vals
	}
	return nil
}

func (x *Relation) GetInfo() *Info {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Info) {
				protoimpl.X.UnmarshalField(x, 4)
			}
			var rv *Info
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Info), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *Relation) GetRolesSid() []int32 {
	if x != nil {
		return x.xxx_hidden_RolesSid
	}
	return nil
}

func (x *Relation) GetMemids() []int64 {
	if x != nil {
		return x.xxx_hidden_Memids
	}
	return nil
}

func (x *Relation) GetTypes() []Relation_MemberType {
	if x != nil {
		return x.xxx_hidden_Types
	}
	return nil
}

func (x *Relation) SetId(v int64) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *Relation) SetKeys(v []uint32) {
	x.xxx_hidden_Keys = v
}

func (x *Relation) SetVals(v []uint32) {
	x.xxx_hidden_Vals = v
}

func (x *Relation) SetInfo(v *Info) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Info, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
	}
}

func (x *Relation) SetRolesSid(v []int32) {
	x.xxx_hidden_RolesSid = v
}

func (x *Relation) SetMemids(v []int64) {
	x.xxx_hidden_Memids = v
}

func (x *Relation) SetTypes(v []Relation_MemberType) {
	x.xxx_hidden_Types = v
}

func (x *Relation) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Relation) HasInfo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Relation) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *Relation) ClearInfo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Info, (*Info)(nil))
}

type Relation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int64
	// Parallel arrays.
	Keys []uint32
	Vals []uint32
	Info *Info
	// Parallel arrays
	RolesSid []int32
	// consistency, but it is now too late to change it
	Memids []int64
	Types  []Relation_MemberType
}

func (b0 Relation_builder) Build() *Relation {
	m0 := &Relation{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = *b.Id
	}
	x.xxx_hidden_Keys = b.Keys
	x.xxx_hidden_Vals = b.Vals
	if b.Info != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Info = b.Info
	}
	x.xxx_hidden_RolesSid = b.RolesSid
	x.xxx_hidden_Memids = b.Memids
	x.xxx_hidden_Types = b.Types
	return m0
}

var File_osmproto_osmformat_proto protoreflect.FileDescriptor

const file_osmproto_osmformat_proto_rawDesc = "" +
	"\n" +
	"\x18osmproto/osmformat.proto\x12\bosmproto\"\xa9\x03\n" +
	"\vHeaderBlock\x12,\n" +
	"\x04bbox\x18\x01 \x01(\v2\x14.osmproto.HeaderBBoxB\x02(\x01R\x04bbox\x12+\n" +
	"\x11required_features\x18\x04 \x03(\tR\x10requiredFeatures\x12+\n" +
	"\x11optional_features\x18\x05 \x03(\tR\x10optionalFeatures\x12&\n" +
	"\x0ewritingprogram\x18\x10 \x01(\tR\x0ewritingprogram\x12\x16\n" +
	"\x06source\x18\x11 \x01(\tR\x06source\x12B\n" +
	"\x1dosmosis_replication_timestamp\x18  \x01(\x03R\x1bosmosisReplicationTimestamp\x12M\n" +
	"#osmosis_replication_sequence_number\x18! \x01(\x03R osmosisReplicationSequenceNumber\x12?\n" +
	"\x1cosmosis_replication_base_url\x18\" \x01(\tR\x19osmosisReplicationBaseUrl\"`\n" +
	"\n" +
	"HeaderBBox\x12\x12\n" +
	"\x04left\x18\x01 \x01(\x12R\x04left\x12\x14\n" +
	"\x05right\x18\x02 \x01(\x12R\x05right\x12\x10\n" +
	"\x03top\x18\x03 \x01(\x12R\x03top\x12\x16\n" +
	"\x06bottom\x18\x04 \x01(\x12R\x06bottom\"\xab\x02\n" +
	"\x0ePrimitiveBlock\x127\n" +
	"\vstringtable\x18\x01 \x01(\v2\x15.osmproto.StringTableR\vstringtable\x12D\n" +
	"\x0eprimitivegroup\x18\x02 \x03(\v2\x18.osmproto.PrimitiveGroupB\x02(\x01R\x0eprimitivegroup\x12%\n" +
	"\vgranularity\x18\x11 \x01(\x05:\x03100R\vgranularity\x12 \n" +
	"\n" +
	"lat_offset\x18\x13 \x01(\x03:\x010R\tlatOffset\x12 \n" +
	"\n" +
	"lon_offset\x18\x14 \x01(\x03:\x010R\tlonOffset\x12/\n" +
	"\x10date_granularity\x18\x12 \x01(\x05:\x041000R\x0fdateGranularity\"\x80\x02\n" +
	"\x0ePrimitiveGroup\x12(\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0e.osmproto.NodeB\x02(\x01R\x05nodes\x12.\n" +
	"\x05dense\x18\x02 \x01(\v2\x14.osmproto.DenseNodesB\x02(\x01R\x05dense\x12%\n" +
	"\x04ways\x18\x03 \x03(\v2\r.osmproto.WayB\x02(\x01R\x04ways\x124\n" +
	"\trelations\x18\x04 \x03(\v2\x12.osmproto.RelationB\x02(\x01R\trelations\x127\n" +
	"\n" +
	"changesets\x18\x05 \x03(\v2\x13.osmproto.ChangeSetB\x02(\x01R\n" +
	"changesets\"\x1b\n" +
	"\vStringTable\x12\f\n" +
	"\x01s\x18\x01 \x03(\tR\x01s\"\xa7\x01\n" +
	"\x04Info\x12\x1c\n" +
	"\aversion\x18\x01 \x01(\x05:\x02-1R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tchangeset\x18\x03 \x01(\x03R\tchangeset\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x05R\x03uid\x12\x19\n" +
	"\buser_sid\x18\x05 \x01(\rR\auserSid\x12\x18\n" +
	"\avisible\x18\x06 \x01(\bR\avisible\"\xa8\x01\n" +
	"\tDenseInfo\x12\x18\n" +
	"\aversion\x18\x01 \x03(\x05R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x03(\x12R\ttimestamp\x12\x1c\n" +
	"\tchangeset\x18\x03 \x03(\x12R\tchangeset\x12\x10\n" +
	"\x03uid\x18\x04 \x03(\x11R\x03uid\x12\x19\n" +
	"\buser_sid\x18\x05 \x03(\x11R\auserSid\x12\x18\n" +
	"\avisible\x18\x06 \x03(\bR\avisible\"\x1b\n" +
	"\tChangeSet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8a\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x12R\x02id\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\rR\x04keys\x12\x12\n" +
	"\x04vals\x18\x03 \x03(\rR\x04vals\x12&\n" +
	"\x04info\x18\x04 \x01(\v2\x0e.osmproto.InfoB\x02(\x01R\x04info\x12\x10\n" +
	"\x03lat\x18\b \x01(\x12R\x03lat\x12\x10\n" +
	"\x03lon\x18\t \x01(\x12R\x03lon\"\x94\x01\n" +
	"\n" +
	"DenseNodes\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x12R\x02id\x125\n" +
	"\tdenseinfo\x18\x05 \x01(\v2\x13.osmproto.DenseInfoB\x02(\x01R\tdenseinfo\x12\x10\n" +
	"\x03lat\x18\b \x03(\x12R\x03lat\x12\x10\n" +
	"\x03lon\x18\t \x03(\x12R\x03lon\x12\x1b\n" +
	"\tkeys_vals\x18\n" +
	" \x03(\x05R\bkeysVals\"\x9d\x01\n" +
	"\x03Way\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\rR\x04keys\x12\x12\n" +
	"\x04vals\x18\x03 \x03(\rR\x04vals\x12&\n" +
	"\x04info\x18\x04 \x01(\v2\x0e.osmproto.InfoB\x02(\x01R\x04info\x12\x12\n" +
	"\x04refs\x18\b \x03(\x12R\x04refs\x12\x10\n" +
	"\x03lat\x18\t \x03(\x12R\x03lat\x12\x10\n" +
	"\x03lon\x18\n" +
	" \x03(\x12R\x03lon\"\x83\x02\n" +
	"\bRelation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\rR\x04keys\x12\x12\n" +
	"\x04vals\x18\x03 \x03(\rR\x04vals\x12&\n" +
	"\x04info\x18\x04 \x01(\v2\x0e.osmproto.InfoB\x02(\x01R\x04info\x12\x1b\n" +
	"\troles_sid\x18\b \x03(\x05R\brolesSid\x12\x16\n" +
	"\x06memids\x18\t \x03(\x12R\x06memids\x123\n" +
	"\x05types\x18\n" +
	" \x03(\x0e2\x1d.osmproto.Relation.MemberTypeR\x05types\"-\n" +
	"\n" +
	"MemberType\x12\b\n" +
	"\x04NODE\x10\x00\x12\a\n" +
	"\x03WAY\x10\x01\x12\f\n" +
	"\bRELATION\x10\x02B6\n" +
	"\rcrosby.binaryZ%github.com/royalcat/osmpbfdb/osmprotob\beditionsp\xe9\a"

var file_osmproto_osmformat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osmproto_osmformat_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_osmproto_osmformat_proto_goTypes = []any{
	(Relation_MemberType)(0), // 0: osmproto.Relation.MemberType
	(*HeaderBlock)(nil),      // 1: osmproto.HeaderBlock
	(*HeaderBBox)(nil),       // 2: osmproto.HeaderBBox
	(*PrimitiveBlock)(nil),   // 3: osmproto.PrimitiveBlock
	(*PrimitiveGroup)(nil),   // 4: osmproto.PrimitiveGroup
	(*StringTable)(nil),      // 5: osmproto.StringTable
	(*Info)(nil),             // 6: osmproto.Info
	(*DenseInfo)(nil),        // 7: osmproto.DenseInfo
	(*ChangeSet)(nil),        // 8: osmproto.ChangeSet
	(*Node)(nil),             // 9: osmproto.Node
	(*DenseNodes)(nil),       // 10: osmproto.DenseNodes
	(*Way)(nil),              // 11: osmproto.Way
	(*Relation)(nil),         // 12: osmproto.Relation
}
var file_osmproto_osmformat_proto_depIdxs = []int32{
	2,  // 0: osmproto.HeaderBlock.bbox:type_name -> osmproto.HeaderBBox
	5,  // 1: osmproto.PrimitiveBlock.stringtable:type_name -> osmproto.StringTable
	4,  // 2: osmproto.PrimitiveBlock.primitivegroup:type_name -> osmproto.PrimitiveGroup
	9,  // 3: osmproto.PrimitiveGroup.nodes:type_name -> osmproto.Node
	10, // 4: osmproto.PrimitiveGroup.dense:type_name -> osmproto.DenseNodes
	11, // 5: osmproto.PrimitiveGroup.ways:type_name -> osmproto.Way
	12, // 6: osmproto.PrimitiveGroup.relations:type_name -> osmproto.Relation
	8,  // 7: osmproto.PrimitiveGroup.changesets:type_name -> osmproto.ChangeSet
	6,  // 8: osmproto.Node.info:type_name -> osmproto.Info
	7,  // 9: osmproto.DenseNodes.denseinfo:type_name -> osmproto.DenseInfo
	6,  // 10: osmproto.Way.info:type_name -> osmproto.Info
	6,  // 11: osmproto.Relation.info:type_name -> osmproto.Info
	0,  // 12: osmproto.Relation.types:type_name -> osmproto.Relation.MemberType
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_osmproto_osmformat_proto_init() }
func file_osmproto_osmformat_proto_init() {
	if File_osmproto_osmformat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osmproto_osmformat_proto_rawDesc), len(file_osmproto_osmformat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osmproto_osmformat_proto_goTypes,
		DependencyIndexes: file_osmproto_osmformat_proto_depIdxs,
		EnumInfos:         file_osmproto_osmformat_proto_enumTypes,
		MessageInfos:      file_osmproto_osmformat_proto_msgTypes,
	}.Build()
	File_osmproto_osmformat_proto = out.File
	file_osmproto_osmformat_proto_goTypes = nil
	file_osmproto_osmformat_proto_depIdxs = nil
}
